Added alignment support
FTBpro/draft-js-export-html pull request #1
Opened 2016-09-20 11:28 UTC by Vall3y

2016-09-22 14:40 UTC, elektronik2k5 commented on lib/stateToHTML.js
> +                var attrString = stringifyAttrs(_attributes2);
Wait what? Why is a compiled file versioned?

2016-09-22 14:41 UTC, elektronik2k5 commented on src/stateToHTML.js
> +
Why hard code it here? Change the package so you can pass these as part of the configuration.

2016-09-22 14:43 UTC, elektronik2k5 commented on src/stateToHTML.js
> +  openWrapperTag(wrapperTag: string, customRendererOptions, blockData) {
A third argument, especially when the second one is optional is problematic. Can you change the function to accept two arguments, when the second one is an object with `customRendererOptions` `blockData` optional properties?

2016-09-22 14:44 UTC, elektronik2k5 commented on src/stateToHTML.js
> +        attributes.class += ` block--align-${alignment}`;
This should be done in the caller site, not hard coded here.

2016-09-22 14:45 UTC, elektronik2k5 requested changes

2016-09-22 14:57 UTC, Vall3y commented on lib/stateToHTML.js
> +                var attrString = stringifyAttrs(_attributes2);
Because I dont use npm publish, instead I refer to a github commit. So the compiled version has to be in the source. Is there a better way to do it?

2016-09-22 14:58 UTC, Vall3y commented on src/stateToHTML.js
> +        attributes.class += ` block--align-${alignment}`;
I know, we've talked about it and we said this would be the fastest solution

2016-09-22 20:07 UTC, elektronik2k5 commented on lib/stateToHTML.js
> +                var attrString = stringifyAttrs(_attributes2);
If we had Babel in the editor, we'd simply require the source files, but we can't yet :(. I plan to change that in the near future. On the mean time, we'll settle for versioning compiled files.

2016-09-25 07:14 UTC, elektronik2k5 approved these changes
Approved as a temporary workaround only

2016-09-25 07:26 UTC, merged