Empty blocks are now rendered as <br> instead of <p><br></p>
FTBpro/draft-js-export-html pull request #4
Opened 2016-10-26 14:35 UTC by Vall3y

2016-10-26 14:38 UTC, Vall3y commented on src/stateToHTML.js
> +    if (block.text.trim() !== '' || isEmptyBlock(blockType)) {
If the text of the block is not empty, or it is an empty block type (such as <hr>), then the start tag should be rendered.

2016-10-26 14:38 UTC, Vall3y commented on src/stateToHTML.js
>        this.output.push(this.renderBlockContent(block));
The block content is rendered either way (in the renderBlockContent, the <br> is rendered. So it needs to be rendered either way)

2016-10-26 14:39 UTC, Vall3y commented
This adds complexity to the code, but at its current state (the repo was a bit messy as we picked it up), I can't think of a way more simple than that to solve this problem. Let me know what you think.

2016-10-27 06:10 UTC, elektronik2k5 requested changes

2016-10-27 06:10 UTC, elektronik2k5 commented on src/stateToHTML.js
> +    if (block.text.trim() !== '' || isEmptyBlock(blockType)) {
```js
const isEmptyText = block.text.trim().length === 0;
const isCurrentBlockEmpty = isEmptyBlock(blockType);
```
then use these twice: here and in `this.writeEndTag(blockType);`

2016-10-27 10:29 UTC, Vall3y commented
@elektronik2k5 done

2016-10-27 11:12 UTC, elektronik2k5 approved these changes

2016-10-27 11:14 UTC, merged